title: <h1 style="color:#2D80DB; font-size:23px;" align="center"> Juan Guillermo Lobaton Galindo</h1>

logo: "/images/picture_me.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/Juan Lobaton Resume AZ.pdf"> Resume</a> |
  <a href="https://www.linkedin.com/in/juan-guillermo-lobaton-galindo-114867169/">LinkedIn</a> |
  <a href=mailto:jg.lobaton@hotmail.com>Email</a> 
 
  </p>
  
  <p align="justify">
  I am actively looking for a job opportunity and pursuing a Master's degree in Data Analytics at University of the Andes (Part-time).
  </p>
  
  
  <h3 style="color:#2D80DB; font-size:15 px;" align="center"> About me</h3>

  
  <p align="justify">
  
  Volleyball ğŸ
  Swimming ğŸŠ
  Succulents ğŸŒµ
  Video Games ğŸ•¹ï¸
  Singing ğŸ¼
  Online Learning ğŸ’»
  
  </p>
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
